name: validate
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Required docs (warn only)
        run: |
          set +e
          for f in README.md docs/CONFIG.md docs/OPERATIONS.md docs/SECURITY.md; do
            [ -f "$f" ] || echo "::warning::$f missing"
          done
