name: validate
on:
  pull_request:
  workflow_dispatch:
  # remove push if you don't want emails on every commit
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Required docs (warn only)
        run: |
          set +e
          for f in README.md docs/CONFIG.md docs/OPERATIONS.md docs/SECURITY.md; do
            if [ ! -f "$f" ]; then echo "::warning::$f missing"; fi
          done
      - name: Secret scan (warn only)
        run: |
          set +e
          if grep -Rni --include='*.md' -e 'xoxb-' -e 'xoxa-' . ; then
            echo "::warning::Possible secret-like string found in docs"
          fi
