name: validate
on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure required files exist (recruiter signals)
        run: |
          test -f README.md
          test -f docs/REDACTION.md
          test -f docs/EVIDENCE.md
          test -f docs/OPERATIONS.md
          test -f docs/ARCHITECTURE.md
          test -f docs/GOVERNANCE.md
          test -f docs/SECURITY.md
          test -f docs/DIAGRAM.md
          test -f CODE_SAMPLES/SlackPhotoService.cls
          test -f CODE_SAMPLES/SlackPhotoBatch.cls
          test -f CODE_SAMPLES/SlackPhotoServiceTest.cls

      - name: Verify Mermaid diagram matches constraints exactly
        run: |
          cat docs/DIAGRAM.md | tr -d ' \t\r\n' | grep -q '`mermaidflowchartTDUser-->SalesforceSalesforce-->|Event|QueueQueue-->External_System`'

      - name: Redaction guard (no secrets, no real hosts)
        run: |
          if grep -RniE '(my\.salesforce\.com|login\.salesforce\.com|slack\.com/api|xoxb-|-----BEGIN)' . ; then
            echo "Potential secret or real host detected. Use placeholders." ; exit 1 ;
          fi

      - name: Placeholder policy present (non-fatal report)
        run: |
          echo 'Check for placeholders (non-fatal):'
          grep -Rni 'NC_\\[SERVICE\\]_JWT' . || true
          grep -Rni '\\[REDACTED\\]' . || true
          echo 'CI checks complete. No org login or deployments performed.'

      - name: Stub lint/static checks (portfolio only)
        run: |
          echo "(stub) run static analysis on Apex and docs here"
          # Real org deployments intentionally omitted in public case study
          # Production pipelines would add packaging/deploy steps behind approvals
